# Generated by Django 5.2 on 2025-11-11 11:00

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="name",
                unique_with=("seller",),
            ),
        ),
    ]
