# Generated by Django 5.2 on 2025-11-16 05:22

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
        ("products", "0005_productauditlog_productimage_remove_product_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ADD", "Item Added"),
                            ("UPDATE", "Item Updated"),
                            ("REMOVE", "Item Removed"),
                            ("CLEAR", "Cart Cleared"),
                        ],
                        max_length=10,
                    ),
                ),
                ("changes", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="cartitem",
            name="price_at_addition",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price of product when added to cart",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["user"], name="carts_cart_user_id_f43479_idx"),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="carts_carti_cart_id_8f3e40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="carts_carti_product_48caae_idx"
            ),
        ),
        migrations.AddField(
            model_name="cartauditlog",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="carts.cart",
            ),
        ),
        migrations.AddField(
            model_name="cartauditlog",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="cartauditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cartauditlog",
            index=models.Index(
                fields=["cart", "-timestamp"], name="carts_carta_cart_id_f0f79f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartauditlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="carts_carta_user_id_44de19_idx"
            ),
        ),
    ]
