# Generated by Django 5.2 on 2025-11-19 18:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_updates",
                    models.BooleanField(
                        default=True, help_text="Receive updates about your orders"
                    ),
                ),
                (
                    "promotions",
                    models.BooleanField(
                        default=True, help_text="Receive promotional emails and offers"
                    ),
                ),
                (
                    "product_restocked",
                    models.BooleanField(
                        default=True,
                        help_text="Get notified when out-of-stock products are back",
                    ),
                ),
                (
                    "newsletter",
                    models.BooleanField(
                        default=False, help_text="Subscribe to our newsletter"
                    ),
                ),
                (
                    "seller_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Receive updates about your store (for sellers)",
                    ),
                ),
                (
                    "new_orders",
                    models.BooleanField(
                        default=True,
                        help_text="Get notified of new orders (for sellers)",
                    ),
                ),
                (
                    "low_stock_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Alert when product stock is low (for sellers)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[("shipping", "Shipping"), ("billing", "Billing")],
                        default="shipping",
                        max_length=10,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("street_address", models.CharField(max_length=255)),
                ("apartment", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                ("delivery_instructions", models.TextField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Addresses",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="profiles_ad_user_id_34c3e0_idx",
                    ),
                    models.Index(
                        fields=["user", "address_type"],
                        name="profiles_ad_user_id_fb6bde_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="profiles_pr_user_id_3364d1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProfileAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("profile_created", "Profile Created"),
                            ("profile_updated", "Profile Updated"),
                            ("avatar_changed", "Avatar Changed"),
                            ("address_added", "Address Added"),
                            ("address_updated", "Address Updated"),
                            ("address_deleted", "Address Deleted"),
                            ("seller_profile_created", "Seller Profile Created"),
                            ("seller_profile_updated", "Seller Profile Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="profiles_pr_user_id_de146c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(max_length=255, unique=True)),
                (
                    "store_slug",
                    models.SlugField(blank=True, max_length=255, unique=True),
                ),
                ("store_description", models.TextField(blank=True, max_length=1000)),
                (
                    "store_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="stores/logos/%Y/%m/"
                    ),
                ),
                (
                    "store_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="stores/banners/%Y/%m/"
                    ),
                ),
                ("return_policy", models.TextField(blank=True, max_length=2000)),
                ("shipping_policy", models.TextField(blank=True, max_length=2000)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store_slug"], name="profiles_se_store_s_a0e5c8_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="profiles_se_is_acti_33f495_idx"
                    ),
                ],
            },
        ),
    ]
